name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

env:
  ACTIVESTATE_CLI_CACHEDIR: ${{ github.workspace }}/.cache        
  ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install State Tool for ActiveState Runtime
      - name: Install State Tool (Linux)
        run: |
          sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
          echo "/home/runner/.local/ActiveState/StateTool/release/bin" >> $GITHUB_PATH
          state --version

      - name: Update ActiveState Project
        run: state pull

      - name: Cache ActiveState CLI
        uses: actions/cache@v1
        env:
          cache-name: cache-platform-build
        with:
          path: ${{ env.ACTIVESTATE_CLI_CACHEDIR }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('activestate.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Lint with flake8
        run: state run lints

      - name: Test with pytest
        run: state run tests

      - name: Build & push Docker image to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: hasnatabk/github-actions
          tags: v1, latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: Dockerfile

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate Docker to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778602549455.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push Docker Image to ECR
        run: |
          docker tag hasnatabk/github-actions:latest 778602549455.dkr.ecr.us-east-1.amazonaws.com/github-actions:latest
          docker push 778602549455.dkr.ecr.us-east-1.amazonaws.com/github-actions:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region us-east-1 update-kubeconfig --name github-actions

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/calculator-app
