name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile calculator.py

      - name: Build & push Docker image to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: hasnatabk/github-actions
          tags: v1, latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: Dockerfile

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate Docker to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778602549455.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push Docker Image to ECR
        run: |
          docker tag hasnatabk/github-actions:latest 778602549455.dkr.ecr.us-east-1.amazonaws.com/github-actions:latest
          docker push 778602549455.dkr.ecr.us-east-1.amazonaws.com/github-actions:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region us-east-1 update-kubeconfig --name my-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/my-deployment
